# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clueTitle', models.CharField(max_length=50)),
                ('clueContent', models.CharField(max_length=1000)),
                ('markerListData', models.CharField(max_length=2000)),
                ('imageId', models.CharField(max_length=20)),
                ('workerId', models.CharField(max_length=20)),
            ],
        ),
       
    ]
